//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDF_BloodRequest
    {
        public int RequestID { get; set; }
        public Nullable<long> SenderAccount_id { get; set; }
        public Nullable<long> ReceiverAccount_id { get; set; }
        public string BloodRequireAddress { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> No_Of_Days { get; set; }
        public string RequestType { get; set; }
        public Nullable<bool> IsOperationDone { get; set; }
    
        public virtual BDF_UserProfile BDF_UserProfile { get; set; }
        public virtual BDF_UserProfile BDF_UserProfile1 { get; set; }
    }
}
