//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDF_UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BDF_UserAccount()
        {
            this.BDF_UserProfile = new HashSet<BDF_UserProfile>();
        }
    
        public long AccountID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<byte> RoleID { get; set; }
        public string Email { get; set; }
    
        public virtual BDF_UserRole BDF_UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BDF_UserProfile> BDF_UserProfile { get; set; }
    }
}
