//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodDonor_APIEntities1 : DbContext
    {
        public BloodDonor_APIEntities1()
            : base("name=BloodDonor_APIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BDF_UserRole> BDF_UserRole { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<BDF_BloodRequest> BDF_BloodRequest { get; set; }
        public virtual DbSet<MedicalReport_Images> MedicalReport_Images { get; set; }
        public virtual DbSet<BDF_UserAccount> BDF_UserAccount { get; set; }
        public virtual DbSet<BDF_UserProfile> BDF_UserProfile { get; set; }
        public virtual DbSet<UserProfile_Images> UserProfile_Images { get; set; }
    }
}
