//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalReport_Images
    {
        public long ImageID { get; set; }
        public Nullable<long> ProfileID { get; set; }
        public string ImagePath { get; set; }
        public string MedicalReport_Status { get; set; }
    
        public virtual BDF_UserProfile BDF_UserProfile { get; set; }
    }
}
