//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduation_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public long QuestionID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string User_Question { get; set; }
        public string Answer { get; set; }
        public string receiverRole { get; set; }
    
        public virtual BDF_UserProfile BDF_UserProfile { get; set; }
    }
}
